### ISSUE TITLE
LAN口地址重启会随机变化

### ISSUE THREAD

**Issue by cerellean** [QiuSimons/R4S-OpenWrt#6]
2个问题：
27号的版本重启LAN口地址会随机变化
另外LAN口的绿灯不亮是源码的问题？

**Comment by QiuSimons** [comment]
mac地址？

**Comment by cerellean** [comment]
> mac地址？

是的
重新刷了3号的固件，貌似这个BUG修复了！MAC地址固定不变了。

**Comment by cerellean** [comment]
4号的固件LAN口获取不到IP了- -！

**Comment by cerellean** [comment]
另外反应个问题，做旁路由的时候，好像不能翻墙，我不知道是我设置问题还是都是这个问题。翻墙用的是PASSWALL。

**Comment by QiuSimons** [comment]
> 4号的固件LAN口获取不到IP了- -！

测试了下没问题，建议重置下，或者完全擦除卡以后，重新写盘
顺便，我不使用旁路由，而且旁路由翻不了墙大概率和固件无关，设置姿势有问题罢了
