### ISSUE TITLE
passwall负载均衡无法启动

### ISSUE THREAD

**Issue by fly127** [QiuSimons/R4S-OpenWrt#7]
12.29稳定版，passwall 负载均衡无法启动，passwall 首页图标显示未启动，设置了用户和密码后，没有显示进入负载均衡入口按钮，通过192.168.1.1:1188也无法进入控制台，不知道是否个案。

**Comment by zengjialuo2020** [comment]
> 12.29稳定版，passwall负载均衡无法启动，passwall主页图标显示未启动，设置了用户和密码后，没有显示进入负载均衡入口按钮，通过192.168.1.1:1188也无法进入控制台，不知道是否个案。
是个案  不行 就多刷两遍，或则至少要重启两次以上就好了。要嘛就重置。我就是tcp显示未运行，可是也能上网。重刷就好了。负载均衡我现在就用，没问题

**Comment by fly127** [comment]
那现在你的tcp显示正常吗？

**Comment by fly127** [comment]
12.26，应该是好的，通过open-wrt 备份/升级，下载到电脑上传升级后，12.27版以后，的passwall，负载均衡就无法启动了，这期间通过卡刷，刷过天灵的最新版固件，后又卡刷回404大佬的12.29稳定版，由于ext4格式，我通常会刷两遍，发现还是无法启动负载均衡，还请大佬看一下。

**Comment by QiuSimons** [comment]
测试了下没遇到
