### ISSUE TITLE
R4S的使用带Docker版本的固件后，OpenWRT端口映射功能失效

### ISSUE THREAD

**Issue by sdcb** [QiuSimons/R4S-OpenWrt#8]
![image](https://user-images.githubusercontent.com/1317141/103607541-231ecb80-4f54-11eb-865e-33137df87a9b.png)

即使使用iptables命令也不能做局域网端口映射。
切换回不带Docker版本的固件后，防火墙中的端口映射功能回归正常。

网上找到了一个相同的问题：
https://koolshare.cn/thread-155213-1-1.html

**Comment by QiuSimons** [comment]
Docker版出现任何异常，都属于正常情况，所以不建议使用docker版
